name: Databricks Deployment

# Trigger workflow on push to dev or main branches
on:
  push:
    branches:
      - dev
      - main

# Environment variables
env:
  DATABRICKS_HOST: https://adb-984752964297111.11.azuredatabricks.net/
  PYTHON_VERSION: '3.9'

jobs:
  deploy:
    name: Deploy to Databricks
    runs-on: ubuntu-latest
    outputs:
      target-environment: ${{ steps.environment.outputs.target }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Step 3: Install Databricks CLI
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/master/install.sh | sh

      # Step 4: Determine target environment based on branch
      - name: Determine target environment
        id: environment
        run: |
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "target=dev" >> $GITHUB_OUTPUT
            echo "Deploying to DEV environment"
          elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "target=prod" >> $GITHUB_OUTPUT
            echo "Deploying to PROD environment"
          else
            echo "Branch ${{ github.ref }} is not configured for deployment"
            exit 1
          fi

      # Step 5: Configure Databricks Authentication
      - name: Configure Databricks Authentication
        run: |
          echo "Setting up Databricks authentication"
          echo "Host: ${{ env.DATABRICKS_HOST }}"
          echo "Authentication will use Service Principal"
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

      # Step 6: Validate Databricks bundle
      - name: Validate Databricks bundle
        run: |
          echo "Validating Databricks bundle configuration for ${{ steps.environment.outputs.target }} environment"
          databricks bundle validate --target ${{ steps.environment.outputs.target }}
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

      # Step 7: Deploy Databricks bundle
      - name: Deploy Databricks bundle
        run: |
          echo "Deploying to ${{ steps.environment.outputs.target }} environment"
          databricks bundle deploy --target ${{ steps.environment.outputs.target }}
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

      # Step 8: Mark deployment as successful
      - name: Mark deployment as successful
        if: success()
        run: |
          echo "Deployment completed successfully to ${{ steps.environment.outputs.target }}"
          echo "DEPLOYMENT_STATUS=success" >> $GITHUB_ENV

      # Step 9: Mark deployment as failed
      - name: Mark deployment as failed
        if: failure()
        run: |
          echo "::error::Deployment failed to ${{ steps.environment.outputs.target }}"
          echo "DEPLOYMENT_STATUS=failed" >> $GITHUB_ENV

  post-deployment:
    name: Post-deployment verification
    runs-on: ubuntu-latest
    needs: deploy
    if: success()

    steps:
      - name: Display post-deployment information
        run: |
          echo "Deployment to ${{ needs.deploy.outputs.target-environment }} completed successfully"
          echo "Jobs are now available in your Databricks workspace"
          echo "You can run jobs manually using:"
          echo "databricks bundle run data_ingestion_job --target ${{ needs.deploy.outputs.target-environment }}"
